# Conexión a la base de datos MySQL en Aiven
spring.datasource.url=jdbc:mysql://rado-bd-mateohiguitap-f7f5.a.aivencloud.com:13075/defaultdb?sslMode=REQUIRED
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_ZeLwFbMSQ6P3G7Y6f9S
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración de Hibernate para que cree las tablas automáticamente
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true